### ISSUE TITLE
Why does my output image appear like this? I used the ABMF2400.22o format along with the corresponding BRDC navigation file from IGS.

### ISSUE THREAD

**Issue by black749** [paarnes/GNSS_Multipath_Analysis_Software#17]
[Barplot_RMS_all.pdf](https://github.com/paarnes/GNSS_Multipath_Analysis_Software/files/12299197/Barplot_RMS_all.pdf)
![BeiDou_C2I_C6I_MP_combined](https://github.com/paarnes/GNSS_Multipath_Analysis_Software/assets/132821278/7cb0c45f-8ec0-4572-8d32-18001862ef07)
![BeiDou_C6I_C2I_MP_combined](https://github.com/paarnes/GNSS_Multipath_Analysis_Software/assets/132821278/d2b31952-9cb3-450e-bf7a-40b8e67baa52)
![BeiDou_C7I_C6I_MP_combined](https://github.com/paarnes/GNSS_Multipath_Analysis_Software/assets/132821278/838a209d-7500-4875-be5f-45aa9287b708)
[BeiDou_ionospheric_delay_combined_L2I_L6I.pdf](https://github.com/paarnes/GNSS_Multipath_Analysis_Software/files/12299198/BeiDou_ionospheric_delay_combined_L2I_L6I.pdf)
[BeiDou_ionospheric_delay_combined_L6I_L2I.pdf](https://github.com/paarnes/GNSS_Multipath_Analysis_Software/files/12299199/BeiDou_ionospheric_delay_combined_L6I_L2I.pdf)
[BeiDou_ionospheric_delay_combined_L7I_L6I.pdf](https://github.com/paarnes/GNSS_Multipath_Analysis_Software/files/12299200/BeiDou_ionospheric_delay_combined_L7I_L6I.pdf)
![Galileo_C1C_C8Q_MP_combined](https://github.com/paarnes/GNSS_Multipath_Analysis_Software/assets/132821278/13f55a2e-0c33-44ef-8e43-95aa1ecc20f3)
![Galileo_C5Q_C8Q_MP_combined](https://github.com/paarnes/GNSS_Multipath_Analysis_Software/assets/132821278/829c6351-43d9-4983-a049-82debc37f3e2)
![Galileo_C6C_C8Q_MP_combined](https://github.com/paarnes/GNSS_Multipath_Analysis_Software/assets/132821278/b7c8d7df-707d-400f-ad02-7a9c441ea863)
![Galileo_C7Q_C8Q_MP_combined](https://github.com/paarnes/GNSS_Multipath_Analysis_Software/assets/132821278/568c783d-b48f-454e-8c17-2b20228c9aa5)
![Galileo_C8Q_C7Q_MP_combined](https://github.com/paarnes/GNSS_Multipath_Analysis_Software/assets/132821278/8b7a534f-f2c1-4575-be33-d3efef3c3ca9)
[Galileo_ionospheric_delay_combined_L1C_L8Q.pdf](https://github.com/paarnes/GNSS_Multipath_Analysis_Software/files/12299203/Galileo_ionospheric_delay_combined_L1C_L8Q.pdf)
[Galileo_ionospheric_delay_combined_L5Q_L8Q.pdf](https://github.com/paarnes/GNSS_Multipath_Analysis_Software/files/12299204/Galileo_ionospheric_delay_combined_L5Q_L8Q.pdf)
[Galileo_ionospheric_delay_combined_L6C_L8Q.pdf](https://github.com/paarnes/GNSS_Multipath_Analysis_Software/files/12299205/Galileo_ionospheric_delay_combined_L6C_L8Q.pdf)
[Galileo_ionospheric_delay_combined_L7Q_L8Q.pdf](https://github.com/paarnes/GNSS_Multipath_Analysis_Software/files/12299206/Galileo_ionospheric_delay_combined_L7Q_L8Q.pdf)
[Galileo_ionospheric_delay_combined_L8Q_L7Q.pdf](https://github.com/paarnes/GNSS_Multipath_Analysis_Software/files/12299207/Galileo_ionospheric_delay_combined_L8Q_L7Q.pdf)
![GLONASS_C1C_C2C_MP_combined](https://github.com/paarnes/GNSS_Multipath_Analysis_Software/assets/132821278/8a08e3fc-4a08-44e2-9002-c593c191540c)
![GLONASS_C1P_C2C_MP_combined](https://github.com/paarnes/GNSS_Multipath_Analysis_Software/assets/132821278/93c9fcd0-3fd1-416c-a265-154ee97b3082)
![GLONASS_C2C_C1C_MP_combined](https://github.com/paarnes/GNSS_Multipath_Analysis_Software/assets/132821278/119d9f2f-2740-4160-a488-2dc9d73c75c5)
![GLONASS_C2P_C1C_MP_combined](https://github.com/paarnes/GNSS_Multipath_Analysis_Software/assets/132821278/26fb80fd-66e1-4d77-b53a-f52566a051ca)
![GLONASS_C3Q_C1C_MP_combined](https://github.com/paarnes/GNSS_Multipath_Analysis_Software/assets/132821278/9bf3baf2-86c0-4218-aab2-a31b4afd97a7)
[GLONASS_ionospheric_delay_combined_L1C_L2C.pdf](https://github.com/paarnes/GNSS_Multipath_Analysis_Software/files/12299208/GLONASS_ionospheric_delay_combined_L1C_L2C.pdf)
[GLONASS_ionospheric_delay_combined_L1P_L2C.pdf](https://github.com/paarnes/GNSS_Multipath_Analysis_Software/files/12299209/GLONASS_ionospheric_delay_combined_L1P_L2C.pdf)
[GLONASS_ionospheric_delay_combined_L2C_L1C.pdf](https://github.com/paarnes/GNSS_Multipath_Analysis_Software/files/12299210/GLONASS_ionospheric_delay_combined_L2C_L1C.pdf)
[GLONASS_ionospheric_delay_combined_L2P_L1C.pdf](https://github.com/paarnes/GNSS_Multipath_Analysis_Software/files/12299211/GLONASS_ionospheric_delay_combined_L2P_L1C.pdf)
[GLONASS_ionospheric_delay_combined_L3Q_L1C.pdf](https://github.com/paarnes/GNSS_Multipath_Analysis_Software/files/12299212/GLONASS_ionospheric_delay_combined_L3Q_L1C.pdf)
![GPS_C1C_C2W_MP_combined](https://github.com/paarnes/GNSS_Multipath_Analysis_Software/assets/132821278/c81a7036-757f-46c4-b547-bb4e08a8960b)
![GPS_C2L_C1C_MP_combined](https://github.com/paarnes/GNSS_Multipath_Analysis_Software/assets/132821278/0a0fe29d-eaff-48e5-ac2a-5ca6a3e72bdd)
![GPS_C2W_C1C_MP_combined](https://github.com/paarnes/GNSS_Multipath_Analysis_Software/assets/132821278/4395873f-3a13-43f8-b083-259f79bb7c11)
![GPS_C5Q_C2L_MP_combined](https://github.com/paarnes/GNSS_Multipath_Analysis_Software/assets/132821278/b457728a-148c-4c49-98c0-c41d04728788)
[GPS_ionospheric_delay_combined_L1C_L2W.pdf](https://github.com/paarnes/GNSS_Multipath_Analysis_Software/files/12299214/GPS_ionospheric_delay_combined_L1C_L2W.pdf)
[GPS_ionospheric_delay_combined_L2L_L1C.pdf](https://github.com/paarnes/GNSS_Multipath_Analysis_Software/files/12299216/GPS_ionospheric_delay_combined_L2L_L1C.pdf)
[GPS_ionospheric_delay_combined_L2W_L1C.pdf](https://github.com/paarnes/GNSS_Multipath_Analysis_Software/files/12299218/GPS_ionospheric_delay_combined_L2W_L1C.pdf)
[GPS_ionospheric_delay_combined_L5Q_L2L.pdf](https://github.com/paarnes/GNSS_Multipath_Analysis_Software/files/12299219/GPS_ionospheric_delay_combined_L5Q_L2L.pdf)
![MP_BeiDou_C2I](https://github.com/paarnes/GNSS_Multipath_Analysis_Software/assets/132821278/857726f5-c060-4db2-9f25-c727f4806a3b)
![MP_BeiDou_C6I](https://github.com/paarnes/GNSS_Multipath_Analysis_Software/assets/132821278/1cc95541-d663-49d1-89c6-7a566f8bf464)
![MP_BeiDou_C7I](https://github.com/paarnes/GNSS_Multipath_Analysis_Software/assets/132821278/00f48434-7ff7-49ff-828a-aad1276989c0)
![MP_Galileo_C1C](https://github.com/paarnes/GNSS_Multipath_Analysis_Software/assets/132821278/1ba0edd9-b92d-4f85-8d53-5877d98800cb)
![MP_Galileo_C5Q](https://github.com/paarnes/GNSS_Multipath_Analysis_Software/assets/132821278/1204b57f-37d1-4349-9208-6a108b00d379)
![MP_Galileo_C6C](https://github.com/paa
[Skyplot_BeiDou.pdf](https://github.com/paarnes/GNSS_Multipath_Analysis_Software/files/12299226/Skyplot_BeiDou.pdf)
rnes/GNSS_Multipath_Analysis_Software/assets/132821278/c0879298-4c19-44df-94ca-48fc7f2291f1)
![MP_Galileo_C7Q](https://github.com/paarnes/GNSS_Multipath_Analysis_Software/assets/132821278/826b6be7-8f9f-4ea1-a409-d96bb98f5d90)
![MP_Galileo_C8Q](https://github.com/paarnes/GNSS_Multipath_Analysis_Software/assets/132821278/829958e1-5a24-41b3-972c-fd86af84abad)
![MP_GLONASS_C1C](https://github.com/paarnes/GNSS_Multipath_Analysis_Software/assets/132821278/6b1f9b5b-b5d6-4c21-8ec8-b5ec3d4b84b8)
o
![MP_GLONASS_C1P](https://github.com/paarnes/GNSS_Multipath_Analysis_Software/assets/132821278/01ed54e7-f6a8-498b-9426-d2caa2d9b02c)
![MP_GLONASS_C2C](https://github.com/paarnes/GNSS_Multipath_Analysis_Software/assets/132821278/0d4cdfd0-34a0-47b6-9809-bf453e9d8191)
![MP_GLONASS_C2P](https://github.com/paarnes/GNSS_Multipath_Analysis_Software/assets/132821278/3dd7b589-37d8-4
![MP_GPS_C1C](https://github.com/paarnes/GNSS_Multipath_Analysis_Software/assets/132821278/25f15086-0f51-4e6f-a51e-70ec07652689)
![MP_GPS_C2L](https://github.com/paarnes/GNSS_Multipath_Analysis_Software/assets/132821278/374edfd5-6e29-4c00-8749-ce551bfa9d3a)
![MP_GPS_C2W](https://github.com/paarnes/GNSS_Multipath_Analysis_Software/assets/132821278/708a2ba2-2e81-4cff-a8a7-7aeb28ae5678)
![MP_GPS_C5Q](https://github.com/paarnes/GNSS_Multipath_Analysis_Software/assets/132821278/1ebf2204-40f2-40a7-b07d-41cb5780a1aa)
9a3-843f-f14829778702)
![MP_GLONASS_C3Q](https://github.com/paarnes/GNSS_Multipath_Analysis_Software/assets/132821278/31f04b92-fcec-4fc8-a186-09525f241c6e)
[Skyplot_Galileo.pdf](https://github.com/paarnes/GNSS_Multipath_Analysis_Software/files/12299227/Skyplot_Galileo.pdf)
[Skyplot_GLONASS.pdf](https://github.com/paarnes/GNSS_Multipath_Analysis_Software/files/12299228/Skyplot_GLONASS.pdf)
[Skyplot_GPS.pdf](https://github.com/paarnes/GNSS_Multipath_Analysis_Software/files/12299229/Skyplot_GPS.pdf)

**Comment by paarnes** [comment]
Hi,
There is a bug in the function that converts coordinates from ECEF to the local ENU system when the receiver position crosses the anti-meridian. Hence the computed satellite elevation angles are wrong. That's the reason for the skyplots and the plots of multipath vs elevation angle look like this. 
Note that this error will not affect the unweighted estimates. Only the ones that include the elevation angles. 

I will fix this as soon as possible.

Best regards,
Per Helge

**Comment by paarnes** [comment]
Bug is fixed and pushed to the master branch. Closing the issue.
