### ISSUE TITLE
The Persistent Bug!

### ISSUE THREAD

**Issue by black749** [paarnes/GNSS_Multipath_Analysis_Software#19]
When testing some new files, bugs appeared again. Many issues arose in their output, such as interrupted execution, incorrect image information, and some being unable to output. 😭😭😭
Testdata : https://drive.google.com/file/d/1wICsipaR8P7VPivasDlscXQqwt2nVg6A/view?usp=sharing

**Comment by paarnes** [comment]
Thank you for providing good test data. I've run through all the files, and fixed the problems. Made a new release now, so I recommend to pull the latest code and try again. It should work now. Please let me know if you still have problems.

Best regards,
Per Helge
