### ISSUE TITLE
New bugs!

### ISSUE THREAD

**Issue by black749** [paarnes/GNSS_Multipath_Analysis_Software#24]
This time, there are two types of problems. The first type is incomplete information in the output image, specifically in the "apsl beri krs1" file. The second type is program errors occurring in the "wuh2 wuhn" file. It is important to note that these two errors have different causes.
https://drive.google.com/file/d/1uR48BeAjNwR_NgrxzNd_PZNCQdKchFgK/view?usp=drive_link

**Comment by paarnes** [comment]
Ok, thanks. This feedback is really good! Will take a look, and come back to you.

**Comment by paarnes** [comment]
These errors are now resolved in the latest release. Please note that the "wuh22440.22o" observation file is not correctly structured. Header information is included outside the header. This is causing problems.

Also, be aware that the  "wuhn22440.22o" has GALILEO in the header, but the observation file does not consist of any GALILEO data. 

![image](https://github.com/paarnes/GNSS_Multipath_Analysis_Software/assets/114779344/5f9d3b91-5b7b-432a-b0b1-c5898d429c52)

Please let me know if you run into some more errors.

Best regards,
Per Helge

**Comment by black749** [comment]
> These errors are now resolved in the latest release. Please note that the "wuh22440.22o" observation file is not correctly structured. Header information is included outside the header. This is causing problems.
> 
> Also, be aware that the "wuhn22440.22o" has GALILEO in the header, but the observation file does not consist of any GALILEO data.
> 
> ![image](https://user-images.githubusercontent.com/114779344/268441754-5f9d3b91-5b7b-432a-b0b1-c5898d429c52.png)
> 
> Please let me know if you run into some more errors.
> 
> Best regards, Per Helge

Thank you very much!
