### ISSUE TITLE
Is there any way to increase the computing speed? Or my data is too large

### ISSUE THREAD

**Issue by morethan-blank** [paarnes/GNSS_Multipath_Analysis_Software#28]
My obs file covers  a whole day, and its sampling interval is 5s . Then the parameter settings are as follows.
>>> from gnssmultipath import GNSS_MultipathAnalysis
>>> obs='/code/igmas/testdata/2023/313/HB03_unique3130.23o'
>>> rnx='/code/igmas/testdata/2023/313/brdm3130.23p'
>>> outdir='/code/igmas/output/2023'
>>> cutoff=10
>>> datarate=30
>>>ana=GNSS_MultipathAnalysis(obs,broadcastNav1=rnx,include_SNR=True,outputDir=outdir,nav_data_rate=datarate,cutoff_elevation_angle=cutoff)
After doing that, a process bar shows
 Computing satellite coordinates, azimuth and elevation angles for desired systems:  39%|██████▌          | (19960/51765)

**Comment by paarnes** [comment]
Hi again,
In the newest release, there are some major speed improvements. 

Please run:
_pip install gnssmultipath==1.4.3_ 

to install the latest version.

Best regards,
Per Helge
