### ISSUE TITLE
want exporting a file

### ISSUE THREAD

**Issue by Baizitang** [paarnes/GNSS_Multipath_Analysis_Software#34]
First of all, thank you very much for open-sourcing your code. 

I'd like to ask, if I want to use this code to read nav/sp3, rinex, and then draw sky plots, SNR plots, etc., while also exporting a file. The columns of the file would include PRN, time, elevation angle, azimuth angle, columns for several bands, satellite system, etc., creating a table file like this. How can I use it? 

Could you please guide me?

**Comment by phaarnes** [comment]
Hi,

You can use the output dictionary to extract the desired information. You could do something like this for instance:
(Also added the example as an attachment. Had to change the filtype to txt, but just change it back to .py)

[example_script.txt](https://github.com/paarnes/GNSS_Multipath_Analysis_Software/files/14071985/example_script.txt)


import os
from gnssmultipath import GNSS_MultipathAnalysis
import numpy as np
from datetime import datetime, timedelta

outputDir = r"C:\Users\perhe\Desktop\GitHub"
rinObs = r"C:\Users\perhe\OneDrive\Documents\Python_skript\GNSS_repo\TestData\ObservationFiles\OPEC00NOR_S_20220010000_01D_30S_MO_3.04.rnx"
rinNav = r"C:\Users\perhe\OneDrive\Documents\Python_skript\GNSS_repo\TestData\NavigationFiles\BRDC00IGS_R_20220010000_01D_MN.rnx"
analysisResults = GNSS_MultipathAnalysis(rinObs,
                                         broadcastNav1=rinNav,
                                         outputDir=outputDir,
                                         include_SNR=True,
                                         plotEstimates=True)


def write_data_to_csv_file(data_lst, file_path):
    """Write a list of strings to a CSV file"""
    with open(file_path, 'w') as file:
        for line in data_lst:
            file.write(line + '\n')

##  Example on how to extract multipath RMS values and put into text file (CSV file)
GNSS_systems = analysisResults["GNSSsystems"]
mp_data_lst = ["System; Band; Code; RMS_MP_AVG"]
for sys in GNSS_systems:
    curr_sys = analysisResults[sys]
    for band in analysisResults[sys]["Bands"]:
        for code in analysisResults[sys][band]["Codes"]:
            curr_code_data = analysisResults[sys][band].get(code)
            rms_multipath_avg = round(curr_code_data["rms_multipath_range1_averaged"],4) if curr_code_data is not None else None
            mp_data_lst.append(f"{sys};{band};{code};{rms_multipath_avg}")
            

file_path = r"C:\Users\perhe\Desktop\GitHub\results.csv"
write_data_to_csv_file(mp_data_lst, file_path)


###  Extract elevation and azimuth angle
def generate_timestamps(tFirstObs, tInterval, tLastObs):
    # Convert tFirstObs to a datetime object
    start_datetime = datetime(*tFirstObs.flatten().astype(int))
    num_epochs = int((tLastObs[3] * 3600 + tLastObs[4] * 60 + tLastObs[5] -
                      (tFirstObs[3] * 3600 + tFirstObs[4] * 60 + tFirstObs[5])) / tInterval) + 1
    # Create a list of timestamps for all epochs
    timestamps = [start_datetime + timedelta(seconds=i * tInterval) for i in range(num_epochs)]
    return timestamps

tFirstObs = analysisResults["ExtraOutputInfo"]["tFirstObs"]
tInterval =  analysisResults["ExtraOutputInfo"]["tInterval"]
tLastObs = analysisResults["ExtraOutputInfo"]["tLastObs"]

time_stamps = generate_timestamps(tFirstObs, tInterval, tLastObs)
### Save the numpy arrays as CSV files


for sys in analysisResults["Sat_position"].keys():
    azimuth = np.round(analysisResults["Sat_position"][sys]["azimuth"],2)
    elevation = np.round(analysisResults["Sat_position"][sys]["elevation"],2)
    headers = ["Sat " + str(i) for i in range(len(azimuth[0]))]
    azimuth_with_headers = np.vstack([headers, azimuth])[:,1::]
    elevation_with_headers = np.vstack([headers, elevation])[:,1::]
    # Transpose the arrays to have timestamps as rows
    azimuth_with_timestamps = np.column_stack([["Time"] + time_stamps, azimuth_with_headers])
    elevation_with_timestamps = np.column_stack([["Time"] + time_stamps, elevation_with_headers])
    # Save array to file
    np.savetxt(outputDir + f'/Satellite_azimuths_{sys}.csv', azimuth_with_timestamps, delimiter=';', fmt='%s')
    np.savetxt(outputDir + f'/Satellite_elevation_{sys}.csv', elevation_with_timestamps, delimiter=';', fmt='%s')


Hope it helps you.

Best regards,
Per Helge

**Comment by paarnes** [comment]
Hi,

You can use the output dictionary to extract the desired data. You can for instance do something like this: (I've attached an  example script that can guide you)

[example_script.txt](https://github.com/paarnes/GNSS_Multipath_Analysis_Software/files/14072007/example_script.txt)

import os
from gnssmultipath import GNSS_MultipathAnalysis
import numpy as np
from datetime import datetime, timedelta

outputDir = r"C:\Users\perhe\Desktop\GitHub"
rinObs = r"C:\Users\perhe\OneDrive\Documents\Python_skript\GNSS_repo\TestData\ObservationFiles\OPEC00NOR_S_20220010000_01D_30S_MO_3.04.rnx"
rinNav = r"C:\Users\perhe\OneDrive\Documents\Python_skript\GNSS_repo\TestData\NavigationFiles\BRDC00IGS_R_20220010000_01D_MN.rnx"
analysisResults = GNSS_MultipathAnalysis(rinObs,
                                         broadcastNav1=rinNav,
                                         outputDir=outputDir,
                                         include_SNR=True,
                                         plotEstimates=True)


def write_data_to_csv_file(data_lst, file_path):
    """Write a list of strings to a CSV file"""
    with open(file_path, 'w') as file:
        for line in data_lst:
            file.write(line + '\n')

###  Example on how to extract multipath RMS values and put into text file (CSV file)
GNSS_systems = analysisResults["GNSSsystems"]
mp_data_lst = ["System; Band; Code; RMS_MP_AVG"]
for sys in GNSS_systems:
    curr_sys = analysisResults[sys]
    for band in analysisResults[sys]["Bands"]:
        for code in analysisResults[sys][band]["Codes"]:
            curr_code_data = analysisResults[sys][band].get(code)
            rms_multipath_avg = round(curr_code_data["rms_multipath_range1_averaged"],4) if curr_code_data is not None else None
            mp_data_lst.append(f"{sys};{band};{code};{rms_multipath_avg}")
            

file_path = r"C:\Users\perhe\Desktop\GitHub\results.csv"
write_data_to_csv_file(mp_data_lst, file_path)


### Extract elevation and azimuth angle
def generate_timestamps(tFirstObs, tInterval, tLastObs):
    # Convert tFirstObs to a datetime object
    start_datetime = datetime(*tFirstObs.flatten().astype(int))
    num_epochs = int((tLastObs[3] * 3600 + tLastObs[4] * 60 + tLastObs[5] -
                      (tFirstObs[3] * 3600 + tFirstObs[4] * 60 + tFirstObs[5])) / tInterval) + 1
    # Create a list of timestamps for all epochs
    timestamps = [start_datetime + timedelta(seconds=i * tInterval) for i in range(num_epochs)]
    return timestamps

tFirstObs = analysisResults["ExtraOutputInfo"]["tFirstObs"]
tInterval =  analysisResults["ExtraOutputInfo"]["tInterval"]
tLastObs = analysisResults["ExtraOutputInfo"]["tLastObs"]

time_stamps = generate_timestamps(tFirstObs, tInterval, tLastObs)

for sys in analysisResults["Sat_position"].keys():
    azimuth = np.round(analysisResults["Sat_position"][sys]["azimuth"],2)
    elevation = np.round(analysisResults["Sat_position"][sys]["elevation"],2)
    headers = ["Sat " + str(i) for i in range(len(azimuth[0]))]
    azimuth_with_headers = np.vstack([headers, azimuth])[:,1::]
    elevation_with_headers = np.vstack([headers, elevation])[:,1::]
    # Transpose the arrays to have timestamps as rows
    azimuth_with_timestamps = np.column_stack([["Time"] + time_stamps, azimuth_with_headers])
    elevation_with_timestamps = np.column_stack([["Time"] + time_stamps, elevation_with_headers])
    # Save array to file
    np.savetxt(outputDir + f'/Satellite_azimuths_{sys}.csv', azimuth_with_timestamps, delimiter=';', fmt='%s')
    np.savetxt(outputDir + f'/Satellite_elevation_{sys}.csv', elevation_with_timestamps, delimiter=';', fmt='%s')



Hope this helps. 

Best regards,
Per Helge

**Comment by Baizitang** [comment]
Dear Per Helge,

First and foremost, I want to express my sincere gratitude for your prompt and informative response. It's truly fortunate for me to receive such guidance from you. 

I will carefully study the example script you provided and I will try to understand the operation mode and data storage structure used by your program.

 Thank you again for not minding my dullness.

Warm regards,

Wang Hengli
